/**
 * BEM AI Knowledge Base
 * 
 * Official grounded knowledge for the BEM AI Assistant.
 * The assistant should use this information rather than inventing functionality.
 * All responses must be based on actual BEM features documented here.
 */

export const bemKnowledge = {

  // ─── PRODUCT OVERVIEW ───────────────────────────────────────
  product: {
    name: "Bharat Earth Monitor",
    shortName: "BEM",
    tagline: "Monitor Bharat. Detect Change. Inform People.",
    description: "Bharat Earth Monitor (BEM) is an India-focused Earth monitoring and information platform designed to bring approved satellite, GNSS, environmental, geographical, and Earth-observation information into one secure and easy-to-use application.",
    workflow: "Receive → Validate → Store → Analyze → Visualize → Review → Approve → Publish",
    simulationWorkflow: "Simulator → SIMULATION DATA → Dashboard → Analysis → Visualization",
    principle: "BEM never presents simulated information as real satellite, GNSS, environmental, or emergency data. All simulated data is clearly marked as SIMULATION DATA.",
    capabilities: [
      "Earth and India monitoring",
      "GNSS data visualization",
      "Satellite/data-source monitoring",
      "Water and land monitoring",
      "Environmental and atmospheric information",
      "Earth/satellite imagery",
      "Change detection",
      "Alert management",
      "Secure data validation",
      "Public information publishing",
      "Reports generation",
      "Admin-controlled publishing",
      "AI-powered user assistance"
    ]
  },

  // ─── DATA CLASSIFICATION ────────────────────────────────────
  dataClassification: {
    SIMULATION_DATA: "Artificial/demo data generated by the application. Always clearly labeled as SIMULATION DATA.",
    PUBLIC: "Approved information visible to People of India.",
    INTERNAL: "Information available only to authorized administrators.",
    RESTRICTED: "Sensitive operational/security information."
  },

  // ─── USER TYPES ─────────────────────────────────────────────
  userTypes: {
    admin: {
      name: "Admin",
      description: "Authorized administrators who can access all BEM operational features.",
      loginMethod: "Email Address + Password",
      access: [
        "Admin Dashboard", "GNSS Receiver", "Satellite Network", "Earth Monitoring",
        "Image Center", "Change Detection", "Alert Center", "Security Center",
        "Reports", "Public Information", "User Management", "Audit Logs", "Settings"
      ]
    },
    publicUser: {
      name: "People of India",
      description: "Public users who can access approved, human-verified Earth monitoring information.",
      loginMethod: "Phone Number + Valid Email ID (NO PASSWORD required)",
      access: [
        "Public Dashboard", "Public Earth Monitoring", "Public Alerts",
        "Public Images", "Public Reports", "Published Environmental Information",
        "User Profile", "BEM AI Assistant"
      ],
      restrictions: "Public users cannot access admin or restricted information."
    }
  },

  // ─── FEATURES ───────────────────────────────────────────────
  features: {

    gnssReceiver: {
      name: "GNSS Receiver",
      route: "/gnss",
      accessLevel: "admin",
      description: "GNSS (Global Navigation Satellite System) visualization module. Displays receiver status, positioning data, and satellite tracking information.",
      fields: ["Receiver status", "Latitude", "Longitude", "Altitude", "Accuracy", "Satellite count", "Signal status", "Timestamp", "Data source"],
      note: "The MVP includes a GNSS Simulator. Every simulated reading is clearly marked as SIMULATION DATA.",
      whatIsGNSS: "GNSS stands for Global Navigation Satellite System. It refers to satellite constellations providing positioning, navigation, and timing (PNT) signals globally. GPS (USA), GLONASS (Russia), Galileo (EU), and NavIC (India) are examples of GNSS systems."
    },

    satelliteNetwork: {
      name: "Satellite / Data Source Network",
      route: "/satellites",
      accessLevel: "admin",
      description: "Manages and monitors satellite data sources and connections. Shows source status, authentication, and data categories.",
      fields: ["Source ID", "Source type", "Status", "Last update", "Data category", "Authentication status", "Connection status"],
      sourceTypes: ["Approved real data sources", "Simulated sources", "Offline sources"]
    },

    earthMonitoring: {
      name: "Earth Monitoring",
      route: "/earth-monitoring",
      accessLevel: "admin",
      description: "Comprehensive Earth monitoring covering water, land, environment, and atmosphere.",
      categories: {
        water: {
          name: "Water Monitoring",
          items: ["Rivers", "Lakes", "Reservoirs", "Water information", "Water-area changes"]
        },
        land: {
          name: "Land / Terrain",
          items: ["Land-use changes", "Terrain information", "Geographic changes", "Mountain/terrain imagery"]
        },
        environment: {
          name: "Environment",
          items: ["Environmental indicators", "Vegetation information", "Land condition"]
        },
        atmosphere: {
          name: "Atmosphere",
          items: ["Air-quality information", "Atmospheric indicators", "Greenhouse-gas information (when supported by legitimate data)"]
        }
      }
    },

    imageCenter: {
      name: "Image Center",
      route: "/images",
      accessLevel: "admin",
      description: "Earth and satellite imagery management. Stores, categorizes, and displays approved imagery with metadata.",
      fields: ["Earth images", "Satellite images", "Region", "Date", "Image source", "Image type", "Metadata", "Classification"],
      features: ["Before/After comparison when appropriate approved datasets are available"]
    },

    changeDetection: {
      name: "Change Detection",
      route: "/change-detection",
      accessLevel: "admin",
      description: "Compares approved Earth-observation data/images to identify possible changes in the environment.",
      categories: ["Water-area change", "Land-use change", "Vegetation change", "Terrain change", "Environmental change"],
      note: "Results are described as POSSIBLE CHANGE DETECTED. Important findings require human review before any public communication."
    },

    alertCenter: {
      name: "Alert Center",
      route: "/alerts",
      accessLevel: "admin",
      description: "Manages Earth monitoring alerts through a structured review and approval workflow.",
      fields: ["Alert ID", "Alert type", "Region", "Severity", "Source", "Timestamp", "Status", "Reviewer", "Approval status"],
      statuses: ["NEW", "UNDER REVIEW", "VERIFIED", "REJECTED", "PUBLISHED", "RESOLVED"],
      workflow: "Incoming Data → Analysis → Possible Alert → Human Review → Verified/Rejected → Admin Approval → Public Alert → Public Dashboard",
      principle: "Unverified information must not automatically become a public alert."
    },

    securityCenter: {
      name: "Security Center",
      route: "/security",
      accessLevel: "admin",
      description: "Monitors incoming data integrity and security events.",
      pipeline: "Incoming Data → Source Identification → Authentication → Integrity Check → Timestamp Validation → Anomaly Detection → Accept/Quarantine",
      monitors: ["Security events", "Failed authentication", "Invalid data", "Source failures", "Suspicious activity", "Admin actions"],
      note: "The security system is defensive and does not implement RF jamming or disruptive interference."
    },

    reports: {
      name: "Reports",
      route: "/reports",
      accessLevel: "admin",
      description: "Generate and manage monitoring reports.",
      adminReports: ["Monitoring summaries", "Earth observations", "Alerts", "Environmental information", "Data-source status", "Security events", "System activity"],
      publicReports: "Public reports contain only approved public information."
    },

    publicPosts: {
      name: "Public Information",
      route: "/public-posts",
      accessLevel: "admin",
      description: "Admins publish approved information for public consumption.",
      fields: ["Title", "Description", "Location", "Date", "Image", "Source", "Category", "Status"],
      categories: ["Earth Monitoring", "Environment", "Water", "Land", "Atmosphere", "Public Alert", "Satellite Update", "Research Update"]
    },

    userManagement: {
      name: "User Management",
      route: "/users",
      accessLevel: "admin",
      description: "Manage user accounts, roles, and verification status."
    },

    auditLogs: {
      name: "Audit Logs",
      route: "/audit-logs",
      accessLevel: "admin",
      description: "Complete audit trail of all system actions, logins, and administrative changes."
    },

    settings: {
      name: "Settings",
      route: "/settings",
      accessLevel: "admin",
      description: "System configuration and application settings."
    },

    publicDashboard: {
      name: "Public Dashboard",
      route: "/public-dashboard",
      accessLevel: "public",
      description: "Shows human-verified Earth monitoring information for People of India.",
      sections: ["India Monitoring Map", "Latest Public Alerts", "Earth Images", "Environmental Information", "Public Reports", "Recent Updates", "User Profile", "BEM AI Assistant"]
    },

    indiaMap: {
      name: "India Monitoring Map",
      accessLevel: "public",
      description: "Interactive map of India showing monitoring data, alerts, and environmental layers.",
      features: ["India outline", "States/regions", "Monitoring points", "Data markers", "Alert markers", "Satellite/data-source markers", "Environmental layers", "Water monitoring layers"],
      interaction: "Selecting a region shows available public information for that area."
    },

    userProfile: {
      name: "User Profile",
      route: "/profile",
      accessLevel: "public",
      description: "Displays user information including name, phone, email, location, and verification status.",
      fields: ["Full Name", "Phone Number", "Email", "Location/City", "Address", "PIN Code", "Verification Status"],
      note: "Users cannot modify their role."
    },

    citizenReporting: {
      name: "Citizen Alert Reporting",
      route: "/dashboard/report-alert",
      accessLevel: "public",
      description: "Allows registered citizens of India to submit real-time Earth observation and incident reports.",
      categories: ["Flood / Water Inundation", "Forest Fire / Wildfire", "Landslide / Ground Movement", "Cyclone / Storm Surge", "Drought / Water Scarcity", "Air Quality / Smog", "Earthquake / Tremor", "Other Environmental Event"],
      workflow: "Submit Form → Confirmation Review → Assign ID (e.g. BEM-ALERT-000001) → Store as PENDING REVIEW → Admin Investigation → Verified / On Hold / Rejected"
    },

    myAlerts: {
      name: "My Alerts",
      route: "/dashboard/my-alerts",
      accessLevel: "public",
      description: "Personal citizen tracking portal displaying submitted reports, real-time review statuses (PENDING, ON HOLD, VERIFIED, REJECTED), and official BEM update notes."
    },

    verifiedAlerts: {
      name: "Verified Public Alerts",
      route: "/dashboard/verified-alerts",
      accessLevel: "public",
      description: "Official public alert feed featuring only admin-verified disaster warnings and Earth-observation advisories."
    }
  },

  // ─── AUTHENTICATION ─────────────────────────────────────────
  authentication: {
    adminLogin: {
      description: "Admin login requires Email Address and Password. Authentication is performed securely.",
      flow: "Admin → Email + Password → Authentication → Role Verification → Admin Dashboard",
      failureMessage: "Invalid admin credentials. Please try again.",
      restrictions: ["Public users cannot create admin accounts", "No public admin registration", "Only authorized administrator accounts can access the Admin Dashboard"]
    },
    publicLogin: {
      description: "People of India login requires Phone Number and Valid Email ID only. There is NO PASSWORD.",
      flow: "Phone + Email → Verification → Authentication → Public Dashboard",
      fields: ["Phone Number (+91 XXXXX XXXXX)", "Valid Email ID"],
      button: "CONTINUE SECURELY"
    },
    publicRegistration: {
      description: "Public registration collects personal information for account creation. No password required.",
      fields: ["Full Name", "Phone Number", "Valid Email ID", "Location / City", "Address", "City PIN Code"],
      button: "CREATE ACCOUNT",
      validation: {
        phone: "Indian phone number with +91, 10-digit mobile number",
        email: "Must be a valid email format",
        pin: "Must contain exactly 6 digits",
        required: "All required fields must be completed"
      }
    }
  },

  // ─── NAVIGATION MAP ─────────────────────────────────────────
  navigation: {
    publicWebsite: {
      path: "/public",
      label: "BEM Public Website",
      description: "The main public-facing BEM website with information about Earth monitoring capabilities."
    },
    login: {
      path: "/login",
      label: "Secure Access Portal",
      description: "Login page for both Admin and People of India."
    },
    register: {
      path: "/register",
      label: "Create Account",
      description: "Registration page for People of India."
    },
    adminDashboard: {
      path: "/",
      label: "Admin Dashboard",
      description: "Main admin overview with system status, metrics, and quick access to all modules.",
      accessLevel: "admin"
    },
    publicDashboard: {
      path: "/public-dashboard",
      label: "Public Dashboard",
      description: "Earth monitoring dashboard for People of India.",
      accessLevel: "public"
    },
    reportAlert: {
      path: "/dashboard/report-alert",
      label: "Report an Alert",
      description: "Citizen alert reporting wizard to submit local observations.",
      accessLevel: "public"
    },
    myAlerts: {
      path: "/dashboard/my-alerts",
      label: "My Alerts",
      description: "Track status of your submitted citizen alert reports.",
      accessLevel: "public"
    },
    verifiedAlerts: {
      path: "/dashboard/verified-alerts",
      label: "Verified Public Alerts",
      description: "Feed of human-verified Earth monitoring advisories.",
      accessLevel: "public"
    },
    profile: {
      path: "/profile",
      label: "User Profile",
      description: "View and manage your profile information.",
      accessLevel: "public"
    }
  },

  // ─── FAQ ────────────────────────────────────────────────────
  faq: [
    {
      q: "What is BEM?",
      a: "Bharat Earth Monitor (BEM) is an India-focused Earth monitoring and information platform that brings approved satellite, GNSS, environmental, geographical, and Earth-observation information together in one secure and easy-to-use application."
    },
    {
      q: "How does BEM work?",
      a: "BEM follows a structured workflow: Receive → Validate → Store → Analyze → Visualize → Review → Approve → Publish. All information goes through validation, human review, and admin approval before being published to the public."
    },
    {
      q: "What is Earth Monitoring?",
      a: "Earth Monitoring in BEM covers four domains: Water (rivers, lakes, reservoirs), Land/Terrain (land-use changes, geographic data), Environment (vegetation, land condition), and Atmosphere (air quality, atmospheric indicators). BEM aggregates approved data from these domains for analysis and public information."
    },
    {
      q: "What is GNSS?",
      a: "GNSS stands for Global Navigation Satellite System. It provides positioning, navigation, and timing information using satellite signals. BEM visualizes GNSS data including receiver status, coordinates (latitude, longitude, altitude), accuracy, and satellite count. The MVP includes a simulator — all simulated readings are clearly marked as SIMULATION DATA."
    },
    {
      q: "How do alerts work?",
      a: "BEM's alert system follows a rigorous workflow: Incoming data is analyzed for potential changes or events. Possible alerts go through human review, where they can be verified or rejected. Only verified alerts that receive admin approval can be published publicly. Unverified information is never automatically published as a public alert."
    },
    {
      q: "What is Simulation Data?",
      a: "Simulation Data is artificial/demo data generated by the BEM application for prototype demonstration purposes. It is always clearly labeled as 'SIMULATION DATA' and is never presented as real satellite, GNSS, environmental, or emergency data."
    },
    {
      q: "What does the India map show?",
      a: "The India Monitoring Map is an interactive map showing India's outline with states/regions, monitoring points, data markers, alert markers, satellite/data-source markers, environmental layers, and water monitoring layers. Selecting a region shows available public information for that area."
    },
    {
      q: "How does the Image Center work?",
      a: "The Image Center stores and manages Earth and satellite imagery. Each image includes metadata such as region, date, source, type, and classification. When appropriate approved datasets are available, BEM supports Before/After comparison to visualize changes over time."
    },
    {
      q: "How can I use BEM?",
      a: "If you are a member of the public (People of India), you can create an account using your phone number and email — no password required. Once logged in, you can access the Public Dashboard to view verified Earth monitoring information, alerts, satellite imagery, environmental data, and reports. You can also use this AI Assistant to learn more about any BEM feature."
    },
    {
      q: "What is Change Detection?",
      a: "Change Detection in BEM compares approved Earth-observation data and images to identify possible changes in water area, land use, vegetation, terrain, and environment. Results are described as 'POSSIBLE CHANGE DETECTED' and important findings require human review before any public communication."
    },
    {
      q: "How does the Security Center work?",
      a: "The Security Center monitors incoming data integrity through a pipeline: Source Identification → Authentication → Integrity Check → Timestamp Validation → Anomaly Detection → Accept/Quarantine. It records security events, failed authentication, invalid data, source failures, and suspicious activity."
    },
    {
      q: "What is the alert workflow?",
      a: "The alert workflow ensures reliability: Incoming Data → Analysis → Possible Alert → Human Review → Verified or Rejected → Admin Approval → Public Alert → Public Dashboard. This ensures no unverified automated information reaches the public."
    },
    {
      q: "How do I create an account?",
      a: "To create a People of India account, go to the registration page and provide: Full Name, Phone Number (+91), Valid Email ID, Location/City, Address, and City PIN Code (6 digits). No password is required. Click 'CREATE ACCOUNT' to register."
    },
    {
      q: "How do I log in?",
      a: "People of India can log in by entering their Phone Number and Valid Email ID — no password needed. Click 'CONTINUE SECURELY' to access the Public Dashboard. Admins log in with their Email Address and Password through the Admin portal."
    },
    {
      q: "What reports are available?",
      a: "Admin reports include monitoring summaries, Earth observations, alerts, environmental information, data-source status, security events, and system activity. Public reports contain only approved, human-verified public information."
    },
    {
      q: "What are satellite data sources?",
      a: "BEM manages various data sources including satellite feeds, GNSS receivers, and environmental sensors. Each source has an ID, type, status, data category, and authentication status. Sources are distinguished as approved real sources, simulated sources, or offline sources."
    },
    {
      q: "How do I report an alert?",
      a: "As a logged-in citizen (People of India), go to 'Report an Alert' in your navigation or dashboard. Select the Event Category (Flood, Forest Fire, Landslide, Cyclone/Storm, etc.), enter the exact location with PIN code, describe what you observed, select the reported threat level, and optionally upload a photo (up to 5MB). After reviewing the details in the confirmation preview, submit the report to receive a unique Tracking ID (e.g. BEM-ALERT-000001)."
    },
    {
      q: "What does PENDING REVIEW mean?",
      a: "Every citizen-submitted alert starts with the status 'PENDING REVIEW'. It is classified as an unverified citizen observation and is never published directly to the public map or feed as a confirmed emergency until an authorized BEM Administrator independently investigates, cross-references satellite telemetry, sets a verified threat level, and approves it."
    },
    {
      q: "How are citizen alerts verified?",
      a: "Incoming citizen reports enter the Admin Alert Center under Citizen Alert Reports. BEM Administrators review the incident location, timestamp, observation photos, and cross-reference them with live satellite passes, radar feeds, and GNSS observations. The administrator then sets a Verified Threat Level (LOW, MODERATE, HIGH, CRITICAL, or DISMISSED) and either ACCEPTS & PUBLISHES it to the public verified feed, puts it ON HOLD for further verification, or REJECTS it with a stated reason."
    },
    {
      q: "Where can I track my submitted alerts?",
      a: "You can track the status of all your submitted alerts in real-time by visiting 'My Alerts' in your dashboard navigation. You'll see current status badges (PENDING, ON HOLD, VERIFIED, REJECTED), administrative review timestamps, and official BEM update notes."
    },
    {
      q: "What is the Verified Public Alerts feed?",
      a: "The Verified Alerts feed displays only alerts that have undergone rigorous administrative review and validation. It filters out unconfirmed reports, showing confirmed incident cards with threat level badges, affected districts, satellite verification timestamps, and official safety advisories."
    }
  ],

  // ─── QUICK QUESTIONS ────────────────────────────────────────
  quickQuestions: [
    "How do I report an alert?",
    "What does PENDING REVIEW mean?",
    "How are citizen alerts verified?",
    "How does BEM work?",
    "What is Earth Monitoring?",
    "What is GNSS?",
    "How do alerts work?",
    "What does the India map show?",
    "How can I use BEM?",
    "What is Simulation Data?",
    "How does the Image Center work?"
  ],

  // ─── PAGE CONTEXT ───────────────────────────────────────────
  pageContext: {
    "/": "You're viewing the Admin Dashboard — the central command center showing system overview, active monitoring, satellite status, and quick access to all BEM modules.",
    "/gnss": "You're on the GNSS Receiver page. I can explain the GNSS readings shown here — latitude, longitude, altitude, accuracy, satellite count, and signal status. Remember that MVP readings are SIMULATION DATA.",
    "/satellites": "You're viewing the Satellite / Data Source Network. This shows all connected data sources, their status, authentication, and connection health.",
    "/earth-monitoring": "You're on the Earth Monitoring page. This covers Water (rivers, lakes, reservoirs), Land/Terrain, Environment (vegetation), and Atmosphere (air quality).",
    "/images": "You're in the Image Center. Here you can view Earth and satellite imagery, along with metadata, classification, and Before/After comparisons.",
    "/change-detection": "You're viewing Change Detection. This module compares Earth-observation data to identify possible changes in water, land, vegetation, terrain, and environment.",
    "/alerts": "You're in the Alert Center. This page displays possible and verified alerts, including the Citizen Alert Reports tab where admins review, hold, or accept citizen submissions.",
    "/security": "You're viewing the Security Center. This monitors incoming data integrity, authentication events, and potential anomalies in the data pipeline.",
    "/reports": "You're on the Reports page. Generate monitoring summaries, alert reports, and environmental information reports.",
    "/public-posts": "You're managing Public Information. From here, admins can publish approved information for People of India.",
    "/users": "You're in User Management. View and manage all user accounts, roles, and verification statuses.",
    "/audit-logs": "You're viewing Audit Logs — a complete record of all system actions, logins, and administrative changes.",
    "/settings": "You're on the Settings page. Configure system preferences and application behavior.",
    "/public-dashboard": "You're on the Public Dashboard — your personalized view of verified Earth monitoring information, alerts, imagery, and environmental data for Bharat.",
    "/dashboard/report-alert": "You're on the Citizen Alert Reporting page. Here you can submit local Earth observations or emergency incidents for verification by BEM administrators.",
    "/dashboard/my-alerts": "You're viewing My Alerts. Here you can track the review status of your submitted reports and view official BEM administrator feedback.",
    "/dashboard/verified-alerts": "You're viewing the Verified Public Alerts feed. All alerts displayed here have been verified by BEM administrators through satellite and telemetry cross-referencing.",
    "/profile": "You're viewing your User Profile — your name, phone, email, location, and verification status.",
    "/public": "You're on the BEM public website. Learn about Bharat Earth Monitor's capabilities, view public alerts, and access the Secure Portal.",
    "/login": "You're at the BEM Secure Access Portal. Choose Admin or People of India to log in.",
    "/register": "You're on the registration page. Create your People of India account with your phone number, email, location, and PIN code."
  }
};
